steps:
  # Install dependencies
  - name: node
    entrypoint: yarn
    args: ["install"]

  # Run custom commands
  - name: node
    entrypoint: yarn
    args: ["run", "build"]

  # Run custom commands
  - name: node
    entrypoint: yarn
    args: ["run", "start"]
